version: '3'
services:
  superna-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-superna-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.local
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=ChangeME
    volumes:
      - ./vlab_superna_api:/usr/lib/python3.8/site-packages/vlab_superna_api
    command: ["python3", "app.py"]

  superna-worker:
    image:
      willnx/vlab-superna-worker
    volumes:
      - ./vlab_superna_api:/usr/lib/python3.8/site-packages/vlab_superna_api
      - /mnt/raid/images/superna:/images:ro
    environment:
      - INF_VCENTER_SERVER=virtlab.local
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=ChangeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  superna-broker:
    image:
      rabbitmq:3.7-alpine
